// Court diagram for each drill, in the little language court.js draws.
// Anchors: n|f (near/far side) + BACK|BL|MID|SL|BOX|NET + lane
// ('' centre, l/r half, lw/rw singles sideline, la/ra alley, lo/ro outside).
// SERVEl/SERVEr = beside the centre mark. Numbers "x,y" are court units
// (x: ±1 singles sidelines, y: ±1 baselines, 0 the net).
// Roles: C coach/feeder, P player, S server, R returner, X waiting, any
// other letter a named player. >a>b ball, ^a>b lob, ~a~b movement.
export const DIAGRAMS = {
  k1: '@open string P:nNET P:fNET >nNET>fNET',
  k2: '@open A:nBOXl B:fBOXl >nBOXl>fBOXl A:nBOXr B:fBOXr >fBOXr>nBOXr',
  k3: '@open scatter:6',
  k4: '@open scatter:5',
  k5: '@open line:-0.95,-0.6>0.95,-0.6 line:-0.95,0.6>0.95,0.6 P:-0.6,-0.6 P:-0.2,-0.6 P:0.2,-0.6 P:0.6,-0.6 ~-0.6,-0.6~-0.6,0.55 ~0.2,-0.6~0.2,0.55 C:1.3,0',
  k6: '@open scatter:6',
  k7: '@open scatter:6',
  k8: '@open line:-0.95,0>0.95,0 A:-0.45,-0.3 B:-0.45,0.3 >-0.45,-0.3>-0.45,0.3 A:0.45,-0.3 B:0.45,0.3 >0.45,0.3>0.45,-0.3',
  k9: '@open P:-1,0 A:-0.45,0 >-1,0>0.7,0 ~-0.45,0.08~0.7,0.08',
  k10: '@open A:0,0.3 B:0,-0.3 o:-0.22,0.12 o:0.22,0.12 ~0,-0.3~-0.22,0.1',
  k11: '@open A:-0.18,0 B:0.18,0 o:-0.4,0.3',
  k12: '@open scatter:6',
  k13: 'A:nSLl A:nSLr A:nMID B:fSLl B:fSLr B:fMID balls:n balls:f >nBOXr>fMIDl >fBOXl>nMIDr',
  k14: 'A:nSLl A:nSL A:nSLr B:fSLl B:fSL B:fSLr C:POSTr >nSL>fBOXl',
  k15: '@open P:-1,-0.5 P:-1,0 P:-1,0.5 o:0.6,-0.5 o:0.6,0 o:0.6,0.5 ~-1,-0.5~0.6,-0.5',
  k16: '@open line:-0.95,0>0.95,0 A:-0.5,-0.4 B:-0.5,0.4 >-0.5,-0.4>-0.5,0.4 A:0.5,-0.4 B:0.5,0.4 >0.5,0.4>0.5,-0.4',
  k17: '@open line:-0.95,0>0.95,0 c:-0.18,0 c:0.18,0 A:0,-0.45 B:0,0.45 >0,-0.45>0,0',
  k18: '@open target:0,0.35 P:-0.65,-0.5 P:0,-0.6 P:0.65,-0.5 >0,-0.6>0,0.35',
  k19: '@open scatter:6',
  k20: '@open C:0,0.4 P:0,-0.35 >0,0.4>0.25,-0.05>0.3,-0.3',
  k21: 'Z:nBoxR Z:fBoxR o:fBOXr o:nBOXr A:nSLr B:fSLr >nSLr>fBOXr',
  k22: 'C:fBOX P:nSL X:nMID X:nBL >fBOX>nSL >nSL>fMIDl',
  k23: 'C:nSLr P:nSL B:fSL >nSLr>nSL >nSL>fSL',
  k24: 'A:nBOXl B:fBOXl >nBOXl>fBOXl A:nBOXr B:fBOXr >fBOXr>nBOXr',
  k25: 'A:nBOXr B:fBOXr >nBOXr>fBOXr o:POSTr',
  k26: 'A:nBOXr B:fBOXr >nBOXr>fBOXr >fBOXr>nBOXr',
  k27: 'A:nSLr B:fSLl ^nSLr>fSLl',
  k28: 'P:nSLr P:nSLl o:nBOXr o:nBOXl',
  k29: 'S:nSLr R:fSLl Z:fBoxL >nSLr>fBOXl >fSLl>nMIDr',
  k30: 'o:nBOXr o:nSLr o:nBLr S:nSLr Z:fBoxL >nSLr>fBOXl',
  k31: 'S:nBOXr R:fBOXl Z:fBoxL >nBOXr>fBOXl',
  k32: 'A:nNETl B:fNETl >nNETl>fNETl A:nNETr B:fNETr >fNETr>nNETr',
  k33: '@open scatter:5',
  k34: 'P:nNETr C:fNETr B:fSLr >fNETr>nNETr >nNETr>fSLr',
  k35: 'A:nSLr B:fSLr ~nSLr~nNETr >fSLr>nNETr',
  k36: '@open A:0,0.4 B:0,-0.2 ~0,-0.2~-0.45,-0.2 ~0,-0.2~0.45,-0.2 >0,0.4>-0.45,-0.12',
  k37: 'A:nBL B:fBL o:nBL o:fBL >nBL>fBLr ~nBL~nBLr',
  k38: 'C:fBOXl C:fBOXr P:nSL >fBOXl>nSLl >fBOXr>nSLr ~nSL~nSLl',
  k39: 'A:nSLr B:fSLl >nSLr>fSLl',
  k40: '@open A:0,-0.45 B:0,0.45 >0,-0.45>0,0.45 ~0,-0.45~0,-0.15',
  k41: 'A:nBOX X:nSL X:nMID B:fBOX X:fSL X:fMID >nBOX>fBOXl',
  k42: 'Z:nBoxes Z:fBoxes A:nBOXl A:nBOXr B:fBOXl B:fBOXr >nBOXl>fBOXr',
  k43: 'A:nBOX B:fBOX >nBOX>fBOXl c:nNETro c:nBOXro c:nSLro c:fNETlo c:fBOXlo c:fSLlo',
  k44: 'A:nMID B:fMID >nMID>fMIDl',
  k45: '@open line:-0.95,0>0.95,0 A:0,-0.45 B:0,0.45 >0,-0.45>0.35,0.4',
  k46: 'A:nMID B:fMID >nMID>fMIDl',
  k47: 'A:nMID B:fMID >nMID>fMIDl c:POSTr c:POSTl',
  k48: '@orange split line:-1,-0.42>1,-0.42 line:-1,0.42>1,0.42 A:nMID B:fMID >nMID>fBOXr',
  k49: '@orange A:nNETl A:nBLr B:fNETr B:fBLl X:fBACK X:fBACKr >fBLl>nBLr',
  k50: 'A:nBLr B:fBLr Z:fHalfR >nBLr>fMIDr',

  gd1: 'P:nSL C:nSLr >nSLr>nSL >nSL>fMID',
  gd2: 'P:nSL C:fNET >fNET>nSL >nSL>fMID',
  gd3: 'P:nSL C:fNET >fNET>nSLl >fNET>nSLr ~nSL~nSLl ~nSL~nSLr',
  gd4: 'P:nSL C:fNET >fNET>nBOX >fNET>nMID ~nSL~nBOX ~nSL~nMID',
  gd5: 'P:nSL C:fBOX >fBOX>nSL >nSL>fBOX',
  gd6: 'A:nBOXr B:fBOXr >nBOXr>fBOXr ~nBOXr~nSLr ~fBOXr~fSLr',
  gd7: 'A:nSLr B:fSLr >nSLr>fSLr ~nSLr~nBLr ~fSLr~fBLr',
  gd8: 'A:nSLr B:fSLl Z:fBoxL Z:nBoxR >nSLr>fBOXl',
  gd9: 'A:nBLr B:fBLr A:nBLl B:fBLl >nBLr>fBLr >fBLl>nBLl',
  gd10: 'A:nBLra B:fBLra Z:fAlleyR Z:nAlleyR >nBLra>fBLra A:nBLla B:fBLla >fBLla>nBLla',
  gd11: 'split A:nBLr B:fBLr Z:fDeepR Z:nDeepR >nBLr>fMIDr',
  gd12: 'net+ A:nBL B:fBL Z:fDeep ^nBL>fMID',
  gd13: 'net+ A:nBLr B:fBLl ^nBLr>fMIDl',
  gd14: 'A:nBLr B:fBLr >nBLr>fMIDr',
  gd15: 'P:nBL C:nMIDl X:nBACK Z:fCornerL Z:fShortR >nMIDl>nBL >nBL>fBLl >nBL>fBOXrw',
  gd16: 'A:nBL B:fBL X:nBACK X:fBACK ^nBL>fMIDl',
  gd17: 'A:nBLr B:fBLr >nBLr>fBLr >fBLr>nBLl',
  gd18: 'line:-0.33,0>-0.33,0.54 line:0.33,0>0.33,0.54 A:nSLr B:fSLl >nSLr>fBOXl',
  gd19: 'A:nBLr B:nBLl D:fBLl E:fBLr C:POSTr >nBLr>fBLl >fBLl>nBLl >nBLl>fBLr',
  gd20: 'A:nBLl B:fBLl >nBLl>fBLl',
  gd21: 'P:nBL C:fNET >fNET>nBL >nBL>fBLlw o:fBLlw o:fBLrw o:fSLlw o:fSLrw o:fBL o:fSL',
  gd22: 'C:fNET P:nBL ~nBL~nBLl ~nBL~nBLr >nBLl>fBLlw >nBLr>fSLlw',
  gd23: 'C:fNET P:nBL >fNET>nMID >fNET>nBOX ~nBL~nBOX',
  gd24: 'C:fNET P:nBL ~nBL~nBLl >fNET>nBLl >nBLl>fBLrw >nBLl>fBLlw',
  gd25: 'split A:nBLr B:fBLl Z:fHalfL Z:nHalfR >nBLr>fBLl',
  gd26: 'split A:nBL B:fBL >nBL>fBLl',
  gd27: 'split A:nBLr B:fBLl Z:fAlleyL >nBLr>fSLlw',
  gd28: 'C:fBACKla P:nBL >fBACKla>nBOXr ~nBL~nSLr >nSLr>fBOXrw ~fBACKla~fBL',
  gd29: 'C:fNET P:nBL >fNET>nBLl >nBLl>fMIDr',
  gd30: 'A:nBLl B:fBLr >nBLl>fBLr',
  gd31: 'C:fNET P:nBL ~nBL~nBLl >fNET>nBLl >nBLl>fMID',
  gd32: 'C:fNET P:nBL ~nBL~nBLl >fNET>nBLl >nBLl>fMID',
  gd33: 'C:fSL P:nSL >fSL>nSLr ~nSL~nSLr',
  gd34: 'P:nBL >nBL>fMID',
  gd35: 'C:fNET P:nBL ~nBL~nBLl >fNET>nBLl >nBLl>fMIDr',
  gd36: 'A:nBL B:fBL >nBL>fBLl >fBLl>nBLr',
  gd37: 'A:nBLr B:nNETl D:fBLl E:fNETr >nBLr>fBLl',

  ss1: '@open A:0,-0.32 B:0,0.32 c:-0.12,0.14 c:0.12,0.14 c:-0.12,-0.14 c:0.12,-0.14 >0,-0.32>0,0.14',
  ss2: 'S:nBACKr S:nBACKl Z:fBoxL >nBACKr>fBOXl >nBACKr>fMIDl >nBACKr>fBACKl',
  ss3: 'A:-1.3,-0.3 B:1.3,-0.3 >-1.3,-0.3>1.3,-0.3',
  ss4: '@open fence A:0,-0.45 B:0,0.45 >0,-0.45>0,0.45',
  ss5: 'S:nSERVEr Z:fBoxL >nSERVEr>fBOXl',
  ss6: 'S:nSLr o:nSERVEr Z:fBoxL >nSLr>fBOXl',
  ss7: 'S:nSERVEr Z:fBoxL',
  ss8: 'o:nSLr o:nBLr o:nBACKr S:nSLr Z:fBoxL >nSLr>fBOXl',
  ss9: 'S:nSERVEr o:0.22,-0.94 Z:fBoxL',
  ss10: '@open P:0,-0.1 o:0.14,0.12',
  ss11: 'S:nSERVEr Z:fBoxL',
  ss12: '@open fence P:0,-0.3',
  ss13: 'S:nSERVEr Z:fBoxL >nSERVEr>fBOXl',
  ss14: 'S:nSERVEr Z:fBoxLW >nSERVEr>fBOXlw',
  ss15: 'S:nSERVEr S:nSERVEl Z:fBoxLT Z:fBoxLW Z:fBoxRT Z:fBoxRW >nSERVEr>fBOXl >nSERVEl>fBOXr',
  ss16: 'net+ S:nSERVEr o:fBOXlw Z:fBoxL ^nSERVEr>fBOXl',
  ss17: 'S:nSERVEr B:fBLl Z:fBoxL >nSERVEr>fBOXl',
  ss18: 'S:nSERVEr Z:fBoxL >nSERVEr>fBOXl',
  ss19: 'S:nSERVEr R:fBLl X:nBACK X:fBACK >nSERVEr>fBOXl',
  sr1: 'S:nSERVEr R:fBLl >nSERVEr>fBOXl >fBLl>nMIDr >nMIDr>fBLrw',
  sr2: 'S:nSERVEr R:fBLl >nSERVEr>fBOXl >fBLl>nMIDr >nMIDr>fBLrw',
  sr3: 'S:nSERVEr R:fBLl Z:nDeep >nSERVEr>fBOXl >fBLl>nMIDr o:fBACKl',
  sr4: 'split S:nSLr R:fBLl >nSLr>fBOXl >fBLl>nBLr',
  sr5: 'S:nSERVEr R:-0.5,0.9 >nSERVEr>fBOXl >-0.5,0.9>nMID',
  sr6: 'S:nSERVEr R:fSLl >nSERVEr>fBOXl >fSLl>nBL',
  sr7: 'A:nNETl B:nBLr X:nBACKr D:fBLl >fBLl>nBLr ~nBLr~nSLr',
  so1: 'A:nNETr B:fBLr ^fBLr>nNETr >nNETr>fMIDr',
  so2: 'A:nBOXl A:nBOXr X:nSLl X:nSLr C:fBL ^fBL>nBOXl',
  so3: 'P:nBOXr C:fBL ^fBL>nSLr ~nBOXr~nSLr ~nSLr~nNETr',
  so4: 'P:nNET o:nBOX o:nSL o:nBL ~nNET~nBL',
  so5: 'P:nNET C:fBL ^fBL>nSL ~nNET~nSL',
  so6: 'A:nNETl B:nBLr D:fNETr E:fBLl ^fBLl>nSLl',
  so7: 'P:nBLl P:nBL P:nBLr ~nBL~nNET',

  nn1: 'A:nNETr B:fNETr >fNETr>nNETr A:nNETl B:fNETl >fNETl>nNETl',
  nn2: 'C:fNETr P:nNETr >fNETr>nNETr >nNETr>fNETr',
  nn3: 'P:nNETl P:nNETr o:nBOXl o:nBOXr B:fSLl B:fSLr o:fBL >fSLl>nNETl',
  nn4: 'P:nSLr C:fNETr ~nSLr~nNETr >fNETr>nBOXr',
  nn5: 'A:nNETr B:fNETr >nNETr>fNETr >fNETr>nNETl',
  nn6: 'A:nBOXr B:fBOXr >nBOXr>fBOXr',
  nn7: 'A:nSL B:fSL c:fBLlw c:fBLrw c:nBLlw c:nBLrw >nSL>fBLlw',
  nn8: 'A:nBOX B:fBOX ~nBOX~nBOXl ~nBOX~nBOXr >nBOX>fBOX',
  nn9: 'A:nSLr B:fSLr ~nSLr~nNETr >fSLr>nNETr',
  nn10: 'A:nNETr B:fBLr ^fBLr>nNETr >nNETr>fMIDr',
  nn11: 'P:nSL B:fBL >fBL>nSL',
  nn12: 'P:nBL C:fNET >fNET>nMID ~nBL~nMID ~nMID~nSL >nMID>fBLlw',
  nn13: 'P:nBL C:fBL c:nMIDlw c:nMIDrw line:-1,-0.62>1,-0.62 >fBL>nBOX ~nBL~nBOX',
  nn14: 'A:nNET A:nBLl A:nBLr B:fNET B:fBLl B:fBLr >nBLr>fBLl',
  nn15: 'A:nNETl A:nBLr B:fNETr B:fBLl ~fBLl~fSLl >nBLr>fBLl',
  nn16: 'S:nSERVEr R:fBLl X:fBACK ^nSERVEr>fBOXl',
  nn17: 'P:nMID C:fBL >fBL>nMID ~nMID~nNET >fBL>nNET',
  nn18: 'A:nNET B:fNET >nNET>fNET',

  nf1: '@open hop:-0.5,0 hop:0.5,0 P:-0.5,-0.75 P:0.5,-0.75',
  nf2: '@open P:-1,0 A:-0.45,0 >-1,0>0.7,0 ~-0.45,0.08~0.7,0.08',
  nf3: '@open A:0,0.4 B:0,-0.2 ~0,-0.2~-0.45,-0.2 ~0,-0.2~0.45,-0.2 >0,0.4>-0.45,-0.12',
  nf4: 'C:fSL P:nBLl P:nBL P:nBLr ~nBL~nBLrw',
  nf5: 'P:nBLl P:nBLr ~nBL~nMIDl~nSL~nBOXr~nNET',
  nf6: 'P:nBOX P:nSL P:nMID ~nSL~nSLr ~nSL~nSLl',
  nf7: 'P:nBL ~nBL~nBLra ~nBL~nBLla',
  nf8: 'P:nBL ~nBL~nMIDr~nSL~nBOXl~nNET',
  nf9: '@open A:-0.25,-0.6 B:0.25,-0.6 ~-0.25,-0.6~-0.25,0.6 ~0.25,-0.6~0.25,0.6 >-0.25,-0.2>0.25,-0.1',
  nf10: 'ladder:0,-0.72 P:-0.95,-0.72',
  nf11: '@open P:0,-0.2 c:-0.5,-0.2 c:0.5,-0.2 c:-0.4,0.25 c:0.4,0.25 c:0,0.32 C:0,0.8',
  nf12: 'P:0,-1 c:-1,-1 c:-0.72,-0.62 c:0,-0.5 c:0.72,-0.62 c:1,-1 B:fBOX ~0,-1~-0.72,-0.62 >fBOX>-0.72,-0.62',
  nf13: 'P:nBL o:nBLlw o:nBLrw o:nSLlw o:nSLrw o:nSL ~nBL~nSLlw ~nBL~nSL',
  nf14: 'P:-1.33,-0.7 c:0,-0.7 ~-1.33,-0.7~1.33,-0.7',
  nf15: 'c:-0.6,-1 c:-0.36,-1 c:-0.12,-1 c:0.12,-1 c:0.36,-1 c:0.6,-1 P:-0.88,-1 ~-0.88,-1~0.88,-1',
  nf16: '@open hex:0,0 P:0,0',
  nf17: 'A:nBOX B:fBOX >nBOX>fBOXr',
  nf18: 'P:nBL C:fNET ~nBL~nMID~nSL >fNET>nSL',
  nf19: 'P:nBLl ~nBLlw~fBLlw~fBLrw~nBLrw',

  ts1: 'split A:nBLr B:fBLl Z:fHalfL Z:nHalfR >nBLr>fBLl',
  ts2: 'A:nBL B:fBL Z:fDeep Z:nDeep >nBL>fMID',
  ts3: 'split A:nBLr B:fBLr Z:fDeepR Z:nDeepR >nBLr>fMIDr',
  ts4: 'split A:nBLr B:fBLl Z:fAlleyL >nBLr>fSLlw',
  ts5: 'C:fBACKla P:nBL >fBACKla>nBOXr ~nBL~nSLr >nSLr>fBOXrw ~fBACKla~fBL',
  ts6: 'S:nSERVEr R:fBLl >nSERVEr>fBOXl >fBLl>nBLr >nBLr>fBLrw',
  ts7: 'S:nSERVEr R:fBLl >nSERVEr>fBOXl >fBLl>nMIDr >nMIDr>fBLrw',
  ts8: 'split S:nSLr R:fBLl >nSLr>fBOXl >fBLl>nBLr',
  ts9: 'A:nBL B:fBL >fBL>nBOX ~nBL~nSL >nSL>fBLlw >fBLlw>nNETr',
  ts10: 'A:nBL B:fBL X:fBACK X:fBACKl X:fBACKr >fBL>nMIDl',
  ts11: 'A:nBL B:fBL >nBL>fBLl',
  ts12: 'A:nBL B:fBL ^nBL>fBL',
  ts13: 'A:nBL B:fBL X:nBACK X:fBACK ^nBL>fMIDl',

  td1: 'A:nBLr B:fBLl D:nSLl E:fSLr >nBLr>fBLl ~fSLr~fNET',
  td2: 'A:nNETr X:nSLr X:nSL C:fBLl >fBLl>nNET ~nNETr~nNET >nNET>fBOXr',
  td3: 'S:nSERVEr A:nNETl C:fBLl >nSERVEr>fBOXl >fBLl>nNET ~nNETl~nNET',
  td4: 'A:nBOX S:nSERVEr R:fBLl ~nBOX~nBOXl ~nSERVEr~nMIDr >nSERVEr>fBOXl',
  td5: 'A:nNETl B:nBLr D:fNETr E:fBLl >nBLr>fBLl',
  td6: 'A:nNETl B:nBLr D:fNETr E:fBLl X:fBACK X:fBACKl >fBLl>nBLr',
  td7: 'A:nBLl B:nBLr D:fNETl E:fNETr ^nBLl>fMIDr',
  td8: 'A:nNETl B:nBLr D:fNETr E:fBLl ~nBLr~nSLr',
  td9: 'A:nBLl B:nBLr D:fBLl E:fBLr M:fBOX >nBLr>fBLl',
  td10: 'A:nNETl B:nBLr D:fNETr E:fBLl >fBLl>nBOXr ~nBLr~nSLr',
  td11: 'A:nBLl B:nBLr D:fBLl E:fBLr >nBLl>fBLl',
  td12: 'A:nBLl B:nNETr D:fBL Z:fCourt >fBL>nBLl',

  tm1: 'S:nSERVEr R:fBLl ~nBLl~nBACK~nSERVEr',
  tm2: 'S:nSERVEr R:fBLl >nSERVEr>fBOXl',
  tm3: 'S:nSERVEr R:fBLl >nSERVEr>fBOXl',
  tm4: 'S:nSERVEr R:fBLl >nSERVEr>fBOXl',
  tm5: 'A:nBL B:fBL >nBL>fMID >fBL>nMID',
  tm7: 'S:nSERVEr R:fBLl >nSERVEr>fBOXl',
  tm8: 'A:nBL B:fBL >nBL>fMID',
  tm9: 'S:nSERVEr R:fBLl >nSERVEr>fBOXl',

  tg1: 'A:nBOX B:fBOX X:nSLro X:nMIDro >nBOX>fBOX ~nSLro~nBOX',
  tg2: 'split A:nBLl B:fBLl D:nBLr E:fBLr >nBLl>fBLl >fBLr>nBLr',
  tg3: 'A:nBL X:nBACK B:fBL X:fBACK >nBL>fBL ~nBL~POSTr~fBACK',
  tg4: 'A:nBL B:fBL X:fBACK >nBL>fBLl',
  tg5: 'A:nBLl A:nBLr B:fBLl B:fBLr >nBLr>fBLl',
  tg6: 'A:nNETl A:nBLr B:fNETr B:fBLl >nBLr>fBLl',
  tg7: 'A:nNETl A:nBLr B:fNETr B:fBLl >nBLr>fBLl',
  tg8: 'C:fNET P:nMIDl P:nMIDr >fNET>nMIDl c:nBACKlo c:nBACKro',
};
